### ISSUE TITLE
Tunes not playing

### ISSUE THREAD

**Issue by edwardabraham** [slow-session/slow-session.github.io#2]
The tunes have been saved with git-lfs, and are not being checked out by Jekyll. Need to revert back to regular git.

https://github.com/slow-session/slow-session.github.io/blob/master/mp3/Connachtman's%20Rambles.mp3

**Comment by tcizadlo** [comment]
is that something we can do? or do we need someone at github to do it?
-Ted

Ted Cizadlo
tcizadlo@gmail.com
Mobile: 0275 964 889
Home:  04 476 7733

___________________
53 Ponsonby Road
Karori Wellington 6012
New Zealand

**Comment by edwardabraham** [comment]
It is definitely something we can do!

**Comment by tcizadlo** [comment]
fixed.
I uninstalled the github desktop for mac, and deleted some binary files and cleaned out some config files and re-uploaded the mp3s.  looks like it worked. ;)
-Ted

Ted Cizadlo
tcizadlo@gmail.com
Mobile: 0275 964 889
Home:  04 476 7733

___________________
53 Ponsonby Road
Karori Wellington 6012
New Zealand

**Comment by edwardabraham** [comment]
Great. Hopefully your setup is back to working just fine!

**Comment by tcizadlo** [comment]
just a little worried about the .gifattributes file, which contains:  *.mp3 filter=lfs diff=lfs merge=lfs -text
Seems a little iffy to me. 
-Ted

Ted Cizadlo
tcizadlo@gmail.com
Mobile: 0275 964 889
Home:  04 476 7733

___________________
53 Ponsonby Road
Karori Wellington 6012
New Zealand

**Comment by edwardabraham** [comment]
Well spotted! That file is the remnant of my git-lfs experiment. I have
deleted it. Pull the changes down and you should be good to go.
