### ISSUE TITLE
"About" file

### ISSUE THREAD

**Issue by tcizadlo** [slow-session/slow-session.github.io#6]
I think Andy has learned how to handle the .md files - and should put it some advice on this page.

**Comment by asjl** [comment]
I've added a file: 

https://github.com/slow-session/slow-session.github.io/blob/master/_tunes/adding_tunes.md

which documents adding a new tune.

**Comment by tcizadlo** [comment]
Nice. Very clear.
My only suggestion is to suggest choosing the ABC with chords, if available? It is often down the session list a little way.

-Ted

Ted Cizadlo
tcizadlo@gmail.com
Mobile: 0275 964 889
Home:  04 476 7733

___________________
53 Ponsonby Road
Karori Wellington 6012
New Zealand

**Comment by asjl** [comment]
If the key matches, yes.
